"""Add identifier and postal_code to battery

Revision ID: 3eed46028961
Revises: 85bdc4a22570
Create Date: 2025-04-01 11:22:13.069467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eed46028961'
down_revision: Union[str, None] = '85bdc4a22570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batteries', sa.Column('identifier', sa.String(), nullable=True))
    op.add_column('batteries', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('batteries', sa.Column('flag', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'batteries', ['identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batteries', type_='unique')
    op.drop_column('batteries', 'flag')
    op.drop_column('batteries', 'postal_code')
    op.drop_column('batteries', 'identifier')
    # ### end Alembic commands ###
