"""battery history2

Revision ID: 55f3be89c3b1
Revises: 091c66ad781d
Create Date: 2025-04-02 15:48:10.954613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f3be89c3b1'
down_revision: Union[str, None] = '091c66ad781d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('battery_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('state_of_charge', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('power_kw', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battery_history')
    # ### end Alembic commands ###
