"""Add IP address

Revision ID: 830b7eb9fc09
Revises: 3d65a4247716
Create Date: 2025-04-02 10:28:29.016817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830b7eb9fc09'
down_revision: Union[str, None] = '3d65a4247716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batteries', sa.Column('IP_address', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'batteries', ['IP_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batteries', type_='unique')
    op.drop_column('batteries', 'IP_address')
    # ### end Alembic commands ###
