"""Initial battery schema

Revision ID: 94b90afecb6b
Revises: 
Create Date: 2025-03-31 11:42:13.629247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# this script is used to manage database migrationsand changes

# revision identifiers, used by Alembic.
# simply put the revision ID here
# and the down revision ID (if any)
# this is used to track the migration history
# and the order in which they should be applied



# revision identifiers, used by Alembic.
revision: str = '94b90afecb6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batteries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('capacity_kwh', sa.Float(), nullable=False),
    sa.Column('state_of_charge', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batteries')
    # ### end Alembic commands ###
