"""Add inverter fields to Battery

Revision ID: ed3ee5c11634
Revises: 94b90afecb6b
Create Date: 2025-03-31 15:10:52.187388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3ee5c11634'
down_revision: Union[str, None] = '94b90afecb6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batteries', sa.Column('power_kw', sa.Float(), nullable=True))
    op.add_column('batteries', sa.Column('voltage', sa.Float(), nullable=True))
    op.add_column('batteries', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('batteries', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batteries', 'last_seen')
    op.drop_column('batteries', 'temperature')
    op.drop_column('batteries', 'voltage')
    op.drop_column('batteries', 'power_kw')
    # ### end Alembic commands ###
